blank_issues_enabled: false
contact_links:
  - name: Payara Forum
    url: https://forum.payara.fish/
    about: Please ask and answer questions about the Payara Platform here.
  - name: Security Issues
    url: https://mailxto.com/smwknx
    about: Write an email to security@payara.fish to report security flaws and vulnerabilities.
